// source: applicants.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.oojob.protobuf.Applicant', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.oojob.protobuf.Applicant = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.oojob.protobuf.Applicant.repeatedFields_, null);
};
goog.inherits(proto.oojob.protobuf.Applicant, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.oojob.protobuf.Applicant.displayName = 'proto.oojob.protobuf.Applicant';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.oojob.protobuf.Applicant.repeatedFields_ = [1,2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.oojob.protobuf.Applicant.prototype.toObject = function(opt_includeInstance) {
  return proto.oojob.protobuf.Applicant.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.oojob.protobuf.Applicant} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oojob.protobuf.Applicant.toObject = function(includeInstance, msg) {
  var f, obj = {
    applicationsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    shortlistedList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    onholdList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    rejectedList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.oojob.protobuf.Applicant}
 */
proto.oojob.protobuf.Applicant.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.oojob.protobuf.Applicant;
  return proto.oojob.protobuf.Applicant.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.oojob.protobuf.Applicant} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.oojob.protobuf.Applicant}
 */
proto.oojob.protobuf.Applicant.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addApplications(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addShortlisted(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addOnhold(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addRejected(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.oojob.protobuf.Applicant.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.oojob.protobuf.Applicant.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.oojob.protobuf.Applicant} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oojob.protobuf.Applicant.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApplicationsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getShortlistedList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getOnholdList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getRejectedList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * repeated string applications = 1;
 * @return {!Array<string>}
 */
proto.oojob.protobuf.Applicant.prototype.getApplicationsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.oojob.protobuf.Applicant} returns this
 */
proto.oojob.protobuf.Applicant.prototype.setApplicationsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.oojob.protobuf.Applicant} returns this
 */
proto.oojob.protobuf.Applicant.prototype.addApplications = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.oojob.protobuf.Applicant} returns this
 */
proto.oojob.protobuf.Applicant.prototype.clearApplicationsList = function() {
  return this.setApplicationsList([]);
};


/**
 * repeated string shortlisted = 2;
 * @return {!Array<string>}
 */
proto.oojob.protobuf.Applicant.prototype.getShortlistedList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.oojob.protobuf.Applicant} returns this
 */
proto.oojob.protobuf.Applicant.prototype.setShortlistedList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.oojob.protobuf.Applicant} returns this
 */
proto.oojob.protobuf.Applicant.prototype.addShortlisted = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.oojob.protobuf.Applicant} returns this
 */
proto.oojob.protobuf.Applicant.prototype.clearShortlistedList = function() {
  return this.setShortlistedList([]);
};


/**
 * repeated string onhold = 3;
 * @return {!Array<string>}
 */
proto.oojob.protobuf.Applicant.prototype.getOnholdList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.oojob.protobuf.Applicant} returns this
 */
proto.oojob.protobuf.Applicant.prototype.setOnholdList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.oojob.protobuf.Applicant} returns this
 */
proto.oojob.protobuf.Applicant.prototype.addOnhold = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.oojob.protobuf.Applicant} returns this
 */
proto.oojob.protobuf.Applicant.prototype.clearOnholdList = function() {
  return this.setOnholdList([]);
};


/**
 * repeated string rejected = 4;
 * @return {!Array<string>}
 */
proto.oojob.protobuf.Applicant.prototype.getRejectedList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.oojob.protobuf.Applicant} returns this
 */
proto.oojob.protobuf.Applicant.prototype.setRejectedList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.oojob.protobuf.Applicant} returns this
 */
proto.oojob.protobuf.Applicant.prototype.addRejected = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.oojob.protobuf.Applicant} returns this
 */
proto.oojob.protobuf.Applicant.prototype.clearRejectedList = function() {
  return this.setRejectedList([]);
};


goog.object.extend(exports, proto.oojob.protobuf);
