// source: permissions.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.github.com.oojob.protobuf.PermissionsBase', null, global);
goog.exportSymbol('proto.github.com.oojob.protobuf.ProfileOperations', null, global);
goog.exportSymbol('proto.github.com.oojob.protobuf.ProfileOperations.ProfileOperationOptions', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.oojob.protobuf.ProfileOperations = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.github.com.oojob.protobuf.ProfileOperations.repeatedFields_, null);
};
goog.inherits(proto.github.com.oojob.protobuf.ProfileOperations, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.github.com.oojob.protobuf.ProfileOperations.displayName = 'proto.github.com.oojob.protobuf.ProfileOperations';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.oojob.protobuf.PermissionsBase = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.com.oojob.protobuf.PermissionsBase, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.github.com.oojob.protobuf.PermissionsBase.displayName = 'proto.github.com.oojob.protobuf.PermissionsBase';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.github.com.oojob.protobuf.ProfileOperations.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.com.oojob.protobuf.ProfileOperations.prototype.toObject = function(opt_includeInstance) {
  return proto.github.com.oojob.protobuf.ProfileOperations.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.com.oojob.protobuf.ProfileOperations} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.ProfileOperations.toObject = function(includeInstance, msg) {
  var f, obj = {
    profileOperationsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.oojob.protobuf.ProfileOperations}
 */
proto.github.com.oojob.protobuf.ProfileOperations.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.oojob.protobuf.ProfileOperations;
  return proto.github.com.oojob.protobuf.ProfileOperations.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.oojob.protobuf.ProfileOperations} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.oojob.protobuf.ProfileOperations}
 */
proto.github.com.oojob.protobuf.ProfileOperations.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Array<!proto.github.com.oojob.protobuf.ProfileOperations.ProfileOperationOptions>} */ (reader.readPackedEnum());
      msg.setProfileOperationsList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.oojob.protobuf.ProfileOperations.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.github.com.oojob.protobuf.ProfileOperations.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.oojob.protobuf.ProfileOperations} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.ProfileOperations.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProfileOperationsList();
  if (f.length > 0) {
    writer.writePackedEnum(
      1,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.github.com.oojob.protobuf.ProfileOperations.ProfileOperationOptions = {
  CREATE: 0,
  READ: 1,
  UPDATE: 2,
  DELETE: 3,
  BULK_UPDATE: 4
};

/**
 * repeated ProfileOperationOptions profile_operations = 1;
 * @return {!Array<!proto.github.com.oojob.protobuf.ProfileOperations.ProfileOperationOptions>}
 */
proto.github.com.oojob.protobuf.ProfileOperations.prototype.getProfileOperationsList = function() {
  return /** @type {!Array<!proto.github.com.oojob.protobuf.ProfileOperations.ProfileOperationOptions>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<!proto.github.com.oojob.protobuf.ProfileOperations.ProfileOperationOptions>} value
 * @return {!proto.github.com.oojob.protobuf.ProfileOperations} returns this
 */
proto.github.com.oojob.protobuf.ProfileOperations.prototype.setProfileOperationsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!proto.github.com.oojob.protobuf.ProfileOperations.ProfileOperationOptions} value
 * @param {number=} opt_index
 * @return {!proto.github.com.oojob.protobuf.ProfileOperations} returns this
 */
proto.github.com.oojob.protobuf.ProfileOperations.prototype.addProfileOperations = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.github.com.oojob.protobuf.ProfileOperations} returns this
 */
proto.github.com.oojob.protobuf.ProfileOperations.prototype.clearProfileOperationsList = function() {
  return this.setProfileOperationsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.com.oojob.protobuf.PermissionsBase.prototype.toObject = function(opt_includeInstance) {
  return proto.github.com.oojob.protobuf.PermissionsBase.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.com.oojob.protobuf.PermissionsBase} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.PermissionsBase.toObject = function(includeInstance, msg) {
  var f, obj = {
    permissionsMap: (f = msg.getPermissionsMap()) ? f.toObject(includeInstance, proto.github.com.oojob.protobuf.ProfileOperations.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.oojob.protobuf.PermissionsBase}
 */
proto.github.com.oojob.protobuf.PermissionsBase.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.oojob.protobuf.PermissionsBase;
  return proto.github.com.oojob.protobuf.PermissionsBase.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.oojob.protobuf.PermissionsBase} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.oojob.protobuf.PermissionsBase}
 */
proto.github.com.oojob.protobuf.PermissionsBase.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getPermissionsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.github.com.oojob.protobuf.ProfileOperations.deserializeBinaryFromReader, "", new proto.github.com.oojob.protobuf.ProfileOperations());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.oojob.protobuf.PermissionsBase.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.github.com.oojob.protobuf.PermissionsBase.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.oojob.protobuf.PermissionsBase} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.PermissionsBase.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPermissionsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.github.com.oojob.protobuf.ProfileOperations.serializeBinaryToWriter);
  }
};


/**
 * map<string, ProfileOperations> permissions = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.github.com.oojob.protobuf.ProfileOperations>}
 */
proto.github.com.oojob.protobuf.PermissionsBase.prototype.getPermissionsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.github.com.oojob.protobuf.ProfileOperations>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.github.com.oojob.protobuf.ProfileOperations));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.github.com.oojob.protobuf.PermissionsBase} returns this
 */
proto.github.com.oojob.protobuf.PermissionsBase.prototype.clearPermissionsMap = function() {
  this.getPermissionsMap().clear();
  return this;};


goog.object.extend(exports, proto.github.com.oojob.protobuf);
