// source: place.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.github.com.oojob.protobuf.Address', null, global);
goog.exportSymbol('proto.github.com.oojob.protobuf.AggregateRating', null, global);
goog.exportSymbol('proto.github.com.oojob.protobuf.GeoLocation', null, global);
goog.exportSymbol('proto.github.com.oojob.protobuf.Place', null, global);
goog.exportSymbol('proto.github.com.oojob.protobuf.Rating', null, global);
goog.exportSymbol('proto.github.com.oojob.protobuf.Review', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.oojob.protobuf.Rating = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.com.oojob.protobuf.Rating, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.github.com.oojob.protobuf.Rating.displayName = 'proto.github.com.oojob.protobuf.Rating';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.oojob.protobuf.AggregateRating = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.com.oojob.protobuf.AggregateRating, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.github.com.oojob.protobuf.AggregateRating.displayName = 'proto.github.com.oojob.protobuf.AggregateRating';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.oojob.protobuf.Review = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.com.oojob.protobuf.Review, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.github.com.oojob.protobuf.Review.displayName = 'proto.github.com.oojob.protobuf.Review';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.oojob.protobuf.GeoLocation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.com.oojob.protobuf.GeoLocation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.github.com.oojob.protobuf.GeoLocation.displayName = 'proto.github.com.oojob.protobuf.GeoLocation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.oojob.protobuf.Address = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.com.oojob.protobuf.Address, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.github.com.oojob.protobuf.Address.displayName = 'proto.github.com.oojob.protobuf.Address';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.oojob.protobuf.Place = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.github.com.oojob.protobuf.Place, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.github.com.oojob.protobuf.Place.displayName = 'proto.github.com.oojob.protobuf.Place';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.com.oojob.protobuf.Rating.prototype.toObject = function(opt_includeInstance) {
  return proto.github.com.oojob.protobuf.Rating.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.com.oojob.protobuf.Rating} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.Rating.toObject = function(includeInstance, msg) {
  var f, obj = {
    author: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bestRating: jspb.Message.getFieldWithDefault(msg, 2, 0),
    explanation: jspb.Message.getFieldWithDefault(msg, 3, ""),
    value: jspb.Message.getFieldWithDefault(msg, 4, 0),
    worstRating: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.oojob.protobuf.Rating}
 */
proto.github.com.oojob.protobuf.Rating.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.oojob.protobuf.Rating;
  return proto.github.com.oojob.protobuf.Rating.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.oojob.protobuf.Rating} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.oojob.protobuf.Rating}
 */
proto.github.com.oojob.protobuf.Rating.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthor(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBestRating(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setExplanation(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setValue(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWorstRating(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.oojob.protobuf.Rating.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.github.com.oojob.protobuf.Rating.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.oojob.protobuf.Rating} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.Rating.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthor();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBestRating();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getExplanation();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getValue();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getWorstRating();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * optional string author = 1;
 * @return {string}
 */
proto.github.com.oojob.protobuf.Rating.prototype.getAuthor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.oojob.protobuf.Rating} returns this
 */
proto.github.com.oojob.protobuf.Rating.prototype.setAuthor = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 best_rating = 2;
 * @return {number}
 */
proto.github.com.oojob.protobuf.Rating.prototype.getBestRating = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.github.com.oojob.protobuf.Rating} returns this
 */
proto.github.com.oojob.protobuf.Rating.prototype.setBestRating = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string explanation = 3;
 * @return {string}
 */
proto.github.com.oojob.protobuf.Rating.prototype.getExplanation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.oojob.protobuf.Rating} returns this
 */
proto.github.com.oojob.protobuf.Rating.prototype.setExplanation = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 value = 4;
 * @return {number}
 */
proto.github.com.oojob.protobuf.Rating.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.github.com.oojob.protobuf.Rating} returns this
 */
proto.github.com.oojob.protobuf.Rating.prototype.setValue = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 worst_rating = 5;
 * @return {number}
 */
proto.github.com.oojob.protobuf.Rating.prototype.getWorstRating = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.github.com.oojob.protobuf.Rating} returns this
 */
proto.github.com.oojob.protobuf.Rating.prototype.setWorstRating = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.com.oojob.protobuf.AggregateRating.prototype.toObject = function(opt_includeInstance) {
  return proto.github.com.oojob.protobuf.AggregateRating.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.com.oojob.protobuf.AggregateRating} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.AggregateRating.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemReviewed: jspb.Message.getFieldWithDefault(msg, 1, ""),
    ratingCount: jspb.Message.getFieldWithDefault(msg, 2, 0),
    reviewCount: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.oojob.protobuf.AggregateRating}
 */
proto.github.com.oojob.protobuf.AggregateRating.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.oojob.protobuf.AggregateRating;
  return proto.github.com.oojob.protobuf.AggregateRating.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.oojob.protobuf.AggregateRating} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.oojob.protobuf.AggregateRating}
 */
proto.github.com.oojob.protobuf.AggregateRating.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setItemReviewed(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRatingCount(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setReviewCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.oojob.protobuf.AggregateRating.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.github.com.oojob.protobuf.AggregateRating.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.oojob.protobuf.AggregateRating} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.AggregateRating.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemReviewed();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRatingCount();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getReviewCount();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional string item_reviewed = 1;
 * @return {string}
 */
proto.github.com.oojob.protobuf.AggregateRating.prototype.getItemReviewed = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.oojob.protobuf.AggregateRating} returns this
 */
proto.github.com.oojob.protobuf.AggregateRating.prototype.setItemReviewed = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 rating_count = 2;
 * @return {number}
 */
proto.github.com.oojob.protobuf.AggregateRating.prototype.getRatingCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.github.com.oojob.protobuf.AggregateRating} returns this
 */
proto.github.com.oojob.protobuf.AggregateRating.prototype.setRatingCount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 review_count = 3;
 * @return {number}
 */
proto.github.com.oojob.protobuf.AggregateRating.prototype.getReviewCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.github.com.oojob.protobuf.AggregateRating} returns this
 */
proto.github.com.oojob.protobuf.AggregateRating.prototype.setReviewCount = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.com.oojob.protobuf.Review.prototype.toObject = function(opt_includeInstance) {
  return proto.github.com.oojob.protobuf.Review.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.com.oojob.protobuf.Review} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.Review.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemReviewed: jspb.Message.getFieldWithDefault(msg, 1, ""),
    aspect: jspb.Message.getFieldWithDefault(msg, 2, ""),
    body: jspb.Message.getFieldWithDefault(msg, 3, ""),
    rating: (f = msg.getRating()) && proto.github.com.oojob.protobuf.Rating.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.oojob.protobuf.Review}
 */
proto.github.com.oojob.protobuf.Review.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.oojob.protobuf.Review;
  return proto.github.com.oojob.protobuf.Review.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.oojob.protobuf.Review} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.oojob.protobuf.Review}
 */
proto.github.com.oojob.protobuf.Review.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setItemReviewed(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAspect(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBody(value);
      break;
    case 4:
      var value = new proto.github.com.oojob.protobuf.Rating;
      reader.readMessage(value,proto.github.com.oojob.protobuf.Rating.deserializeBinaryFromReader);
      msg.setRating(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.oojob.protobuf.Review.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.github.com.oojob.protobuf.Review.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.oojob.protobuf.Review} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.Review.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemReviewed();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAspect();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBody();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRating();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.github.com.oojob.protobuf.Rating.serializeBinaryToWriter
    );
  }
};


/**
 * optional string item_reviewed = 1;
 * @return {string}
 */
proto.github.com.oojob.protobuf.Review.prototype.getItemReviewed = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.oojob.protobuf.Review} returns this
 */
proto.github.com.oojob.protobuf.Review.prototype.setItemReviewed = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string aspect = 2;
 * @return {string}
 */
proto.github.com.oojob.protobuf.Review.prototype.getAspect = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.oojob.protobuf.Review} returns this
 */
proto.github.com.oojob.protobuf.Review.prototype.setAspect = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string body = 3;
 * @return {string}
 */
proto.github.com.oojob.protobuf.Review.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.oojob.protobuf.Review} returns this
 */
proto.github.com.oojob.protobuf.Review.prototype.setBody = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Rating rating = 4;
 * @return {?proto.github.com.oojob.protobuf.Rating}
 */
proto.github.com.oojob.protobuf.Review.prototype.getRating = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Rating} */ (
    jspb.Message.getWrapperField(this, proto.github.com.oojob.protobuf.Rating, 4));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Rating|undefined} value
 * @return {!proto.github.com.oojob.protobuf.Review} returns this
*/
proto.github.com.oojob.protobuf.Review.prototype.setRating = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.github.com.oojob.protobuf.Review} returns this
 */
proto.github.com.oojob.protobuf.Review.prototype.clearRating = function() {
  return this.setRating(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.github.com.oojob.protobuf.Review.prototype.hasRating = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.com.oojob.protobuf.GeoLocation.prototype.toObject = function(opt_includeInstance) {
  return proto.github.com.oojob.protobuf.GeoLocation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.com.oojob.protobuf.GeoLocation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.GeoLocation.toObject = function(includeInstance, msg) {
  var f, obj = {
    elevation: jspb.Message.getFieldWithDefault(msg, 1, 0),
    latitude: jspb.Message.getFieldWithDefault(msg, 2, 0),
    longitude: jspb.Message.getFieldWithDefault(msg, 3, 0),
    postalCode: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.oojob.protobuf.GeoLocation}
 */
proto.github.com.oojob.protobuf.GeoLocation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.oojob.protobuf.GeoLocation;
  return proto.github.com.oojob.protobuf.GeoLocation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.oojob.protobuf.GeoLocation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.oojob.protobuf.GeoLocation}
 */
proto.github.com.oojob.protobuf.GeoLocation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setElevation(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLatitude(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLongitude(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPostalCode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.oojob.protobuf.GeoLocation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.github.com.oojob.protobuf.GeoLocation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.oojob.protobuf.GeoLocation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.GeoLocation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getElevation();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getLatitude();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getLongitude();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getPostalCode();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional int64 elevation = 1;
 * @return {number}
 */
proto.github.com.oojob.protobuf.GeoLocation.prototype.getElevation = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.github.com.oojob.protobuf.GeoLocation} returns this
 */
proto.github.com.oojob.protobuf.GeoLocation.prototype.setElevation = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 latitude = 2;
 * @return {number}
 */
proto.github.com.oojob.protobuf.GeoLocation.prototype.getLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.github.com.oojob.protobuf.GeoLocation} returns this
 */
proto.github.com.oojob.protobuf.GeoLocation.prototype.setLatitude = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 longitude = 3;
 * @return {number}
 */
proto.github.com.oojob.protobuf.GeoLocation.prototype.getLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.github.com.oojob.protobuf.GeoLocation} returns this
 */
proto.github.com.oojob.protobuf.GeoLocation.prototype.setLongitude = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 postal_code = 4;
 * @return {number}
 */
proto.github.com.oojob.protobuf.GeoLocation.prototype.getPostalCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.github.com.oojob.protobuf.GeoLocation} returns this
 */
proto.github.com.oojob.protobuf.GeoLocation.prototype.setPostalCode = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.com.oojob.protobuf.Address.prototype.toObject = function(opt_includeInstance) {
  return proto.github.com.oojob.protobuf.Address.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.com.oojob.protobuf.Address} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.Address.toObject = function(includeInstance, msg) {
  var f, obj = {
    country: jspb.Message.getFieldWithDefault(msg, 1, ""),
    locality: jspb.Message.getFieldWithDefault(msg, 2, ""),
    region: jspb.Message.getFieldWithDefault(msg, 3, ""),
    postalCode: jspb.Message.getFieldWithDefault(msg, 4, 0),
    street: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.oojob.protobuf.Address}
 */
proto.github.com.oojob.protobuf.Address.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.oojob.protobuf.Address;
  return proto.github.com.oojob.protobuf.Address.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.oojob.protobuf.Address} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.oojob.protobuf.Address}
 */
proto.github.com.oojob.protobuf.Address.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountry(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocality(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRegion(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPostalCode(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setStreet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.oojob.protobuf.Address.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.github.com.oojob.protobuf.Address.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.oojob.protobuf.Address} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.Address.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCountry();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLocality();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRegion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPostalCode();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getStreet();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string country = 1;
 * @return {string}
 */
proto.github.com.oojob.protobuf.Address.prototype.getCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.oojob.protobuf.Address} returns this
 */
proto.github.com.oojob.protobuf.Address.prototype.setCountry = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string locality = 2;
 * @return {string}
 */
proto.github.com.oojob.protobuf.Address.prototype.getLocality = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.oojob.protobuf.Address} returns this
 */
proto.github.com.oojob.protobuf.Address.prototype.setLocality = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string region = 3;
 * @return {string}
 */
proto.github.com.oojob.protobuf.Address.prototype.getRegion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.oojob.protobuf.Address} returns this
 */
proto.github.com.oojob.protobuf.Address.prototype.setRegion = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 postal_code = 4;
 * @return {number}
 */
proto.github.com.oojob.protobuf.Address.prototype.getPostalCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.github.com.oojob.protobuf.Address} returns this
 */
proto.github.com.oojob.protobuf.Address.prototype.setPostalCode = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string street = 5;
 * @return {string}
 */
proto.github.com.oojob.protobuf.Address.prototype.getStreet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.oojob.protobuf.Address} returns this
 */
proto.github.com.oojob.protobuf.Address.prototype.setStreet = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.com.oojob.protobuf.Place.prototype.toObject = function(opt_includeInstance) {
  return proto.github.com.oojob.protobuf.Place.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.com.oojob.protobuf.Place} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.Place.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: (f = msg.getAddress()) && proto.github.com.oojob.protobuf.Address.toObject(includeInstance, f),
    review: (f = msg.getReview()) && proto.github.com.oojob.protobuf.Review.toObject(includeInstance, f),
    aggregateRating: (f = msg.getAggregateRating()) && proto.github.com.oojob.protobuf.AggregateRating.toObject(includeInstance, f),
    branchCode: jspb.Message.getFieldWithDefault(msg, 4, ""),
    geo: (f = msg.getGeo()) && proto.github.com.oojob.protobuf.GeoLocation.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.oojob.protobuf.Place}
 */
proto.github.com.oojob.protobuf.Place.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.oojob.protobuf.Place;
  return proto.github.com.oojob.protobuf.Place.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.oojob.protobuf.Place} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.oojob.protobuf.Place}
 */
proto.github.com.oojob.protobuf.Place.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.github.com.oojob.protobuf.Address;
      reader.readMessage(value,proto.github.com.oojob.protobuf.Address.deserializeBinaryFromReader);
      msg.setAddress(value);
      break;
    case 2:
      var value = new proto.github.com.oojob.protobuf.Review;
      reader.readMessage(value,proto.github.com.oojob.protobuf.Review.deserializeBinaryFromReader);
      msg.setReview(value);
      break;
    case 3:
      var value = new proto.github.com.oojob.protobuf.AggregateRating;
      reader.readMessage(value,proto.github.com.oojob.protobuf.AggregateRating.deserializeBinaryFromReader);
      msg.setAggregateRating(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBranchCode(value);
      break;
    case 5:
      var value = new proto.github.com.oojob.protobuf.GeoLocation;
      reader.readMessage(value,proto.github.com.oojob.protobuf.GeoLocation.deserializeBinaryFromReader);
      msg.setGeo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.oojob.protobuf.Place.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.github.com.oojob.protobuf.Place.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.oojob.protobuf.Place} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.oojob.protobuf.Place.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.github.com.oojob.protobuf.Address.serializeBinaryToWriter
    );
  }
  f = message.getReview();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.github.com.oojob.protobuf.Review.serializeBinaryToWriter
    );
  }
  f = message.getAggregateRating();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.github.com.oojob.protobuf.AggregateRating.serializeBinaryToWriter
    );
  }
  f = message.getBranchCode();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getGeo();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.github.com.oojob.protobuf.GeoLocation.serializeBinaryToWriter
    );
  }
};


/**
 * optional Address address = 1;
 * @return {?proto.github.com.oojob.protobuf.Address}
 */
proto.github.com.oojob.protobuf.Place.prototype.getAddress = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Address} */ (
    jspb.Message.getWrapperField(this, proto.github.com.oojob.protobuf.Address, 1));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Address|undefined} value
 * @return {!proto.github.com.oojob.protobuf.Place} returns this
*/
proto.github.com.oojob.protobuf.Place.prototype.setAddress = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.github.com.oojob.protobuf.Place} returns this
 */
proto.github.com.oojob.protobuf.Place.prototype.clearAddress = function() {
  return this.setAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.github.com.oojob.protobuf.Place.prototype.hasAddress = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Review review = 2;
 * @return {?proto.github.com.oojob.protobuf.Review}
 */
proto.github.com.oojob.protobuf.Place.prototype.getReview = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Review} */ (
    jspb.Message.getWrapperField(this, proto.github.com.oojob.protobuf.Review, 2));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Review|undefined} value
 * @return {!proto.github.com.oojob.protobuf.Place} returns this
*/
proto.github.com.oojob.protobuf.Place.prototype.setReview = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.github.com.oojob.protobuf.Place} returns this
 */
proto.github.com.oojob.protobuf.Place.prototype.clearReview = function() {
  return this.setReview(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.github.com.oojob.protobuf.Place.prototype.hasReview = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional AggregateRating aggregate_rating = 3;
 * @return {?proto.github.com.oojob.protobuf.AggregateRating}
 */
proto.github.com.oojob.protobuf.Place.prototype.getAggregateRating = function() {
  return /** @type{?proto.github.com.oojob.protobuf.AggregateRating} */ (
    jspb.Message.getWrapperField(this, proto.github.com.oojob.protobuf.AggregateRating, 3));
};


/**
 * @param {?proto.github.com.oojob.protobuf.AggregateRating|undefined} value
 * @return {!proto.github.com.oojob.protobuf.Place} returns this
*/
proto.github.com.oojob.protobuf.Place.prototype.setAggregateRating = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.github.com.oojob.protobuf.Place} returns this
 */
proto.github.com.oojob.protobuf.Place.prototype.clearAggregateRating = function() {
  return this.setAggregateRating(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.github.com.oojob.protobuf.Place.prototype.hasAggregateRating = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string branch_code = 4;
 * @return {string}
 */
proto.github.com.oojob.protobuf.Place.prototype.getBranchCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.github.com.oojob.protobuf.Place} returns this
 */
proto.github.com.oojob.protobuf.Place.prototype.setBranchCode = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional GeoLocation geo = 5;
 * @return {?proto.github.com.oojob.protobuf.GeoLocation}
 */
proto.github.com.oojob.protobuf.Place.prototype.getGeo = function() {
  return /** @type{?proto.github.com.oojob.protobuf.GeoLocation} */ (
    jspb.Message.getWrapperField(this, proto.github.com.oojob.protobuf.GeoLocation, 5));
};


/**
 * @param {?proto.github.com.oojob.protobuf.GeoLocation|undefined} value
 * @return {!proto.github.com.oojob.protobuf.Place} returns this
*/
proto.github.com.oojob.protobuf.Place.prototype.setGeo = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.github.com.oojob.protobuf.Place} returns this
 */
proto.github.com.oojob.protobuf.Place.prototype.clearGeo = function() {
  return this.setGeo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.github.com.oojob.protobuf.Place.prototype.hasGeo = function() {
  return jspb.Message.getField(this, 5) != null;
};


goog.object.extend(exports, proto.github.com.oojob.protobuf);
