// source: time.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.oojob.protobuf.DaysOfWeek', null, global);
goog.exportSymbol('proto.oojob.protobuf.Time', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.oojob.protobuf.Time = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.oojob.protobuf.Time.repeatedFields_, null);
};
goog.inherits(proto.oojob.protobuf.Time, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.oojob.protobuf.Time.displayName = 'proto.oojob.protobuf.Time';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.oojob.protobuf.Time.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.oojob.protobuf.Time.prototype.toObject = function(opt_includeInstance) {
  return proto.oojob.protobuf.Time.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.oojob.protobuf.Time} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oojob.protobuf.Time.toObject = function(includeInstance, msg) {
  var f, obj = {
    opens: (f = msg.getOpens()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    closes: (f = msg.getCloses()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    daysOfWeekList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    validFrom: (f = msg.getValidFrom()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    validThrough: (f = msg.getValidThrough()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.oojob.protobuf.Time}
 */
proto.oojob.protobuf.Time.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.oojob.protobuf.Time;
  return proto.oojob.protobuf.Time.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.oojob.protobuf.Time} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.oojob.protobuf.Time}
 */
proto.oojob.protobuf.Time.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setOpens(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCloses(value);
      break;
    case 3:
      var value = /** @type {!Array<!proto.oojob.protobuf.DaysOfWeek>} */ (reader.readPackedEnum());
      msg.setDaysOfWeekList(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setValidFrom(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setValidThrough(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.oojob.protobuf.Time.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.oojob.protobuf.Time.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.oojob.protobuf.Time} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.oojob.protobuf.Time.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpens();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCloses();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDaysOfWeekList();
  if (f.length > 0) {
    writer.writePackedEnum(
      3,
      f
    );
  }
  f = message.getValidFrom();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getValidThrough();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp opens = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.oojob.protobuf.Time.prototype.getOpens = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.oojob.protobuf.Time} returns this
*/
proto.oojob.protobuf.Time.prototype.setOpens = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.oojob.protobuf.Time} returns this
 */
proto.oojob.protobuf.Time.prototype.clearOpens = function() {
  return this.setOpens(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.oojob.protobuf.Time.prototype.hasOpens = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp closes = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.oojob.protobuf.Time.prototype.getCloses = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.oojob.protobuf.Time} returns this
*/
proto.oojob.protobuf.Time.prototype.setCloses = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.oojob.protobuf.Time} returns this
 */
proto.oojob.protobuf.Time.prototype.clearCloses = function() {
  return this.setCloses(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.oojob.protobuf.Time.prototype.hasCloses = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated DaysOfWeek days_of_week = 3;
 * @return {!Array<!proto.oojob.protobuf.DaysOfWeek>}
 */
proto.oojob.protobuf.Time.prototype.getDaysOfWeekList = function() {
  return /** @type {!Array<!proto.oojob.protobuf.DaysOfWeek>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<!proto.oojob.protobuf.DaysOfWeek>} value
 * @return {!proto.oojob.protobuf.Time} returns this
 */
proto.oojob.protobuf.Time.prototype.setDaysOfWeekList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!proto.oojob.protobuf.DaysOfWeek} value
 * @param {number=} opt_index
 * @return {!proto.oojob.protobuf.Time} returns this
 */
proto.oojob.protobuf.Time.prototype.addDaysOfWeek = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.oojob.protobuf.Time} returns this
 */
proto.oojob.protobuf.Time.prototype.clearDaysOfWeekList = function() {
  return this.setDaysOfWeekList([]);
};


/**
 * optional google.protobuf.Timestamp valid_from = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.oojob.protobuf.Time.prototype.getValidFrom = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.oojob.protobuf.Time} returns this
*/
proto.oojob.protobuf.Time.prototype.setValidFrom = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.oojob.protobuf.Time} returns this
 */
proto.oojob.protobuf.Time.prototype.clearValidFrom = function() {
  return this.setValidFrom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.oojob.protobuf.Time.prototype.hasValidFrom = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Timestamp valid_through = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.oojob.protobuf.Time.prototype.getValidThrough = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.oojob.protobuf.Time} returns this
*/
proto.oojob.protobuf.Time.prototype.setValidThrough = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.oojob.protobuf.Time} returns this
 */
proto.oojob.protobuf.Time.prototype.clearValidThrough = function() {
  return this.setValidThrough(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.oojob.protobuf.Time.prototype.hasValidThrough = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * @enum {number}
 */
proto.oojob.protobuf.DaysOfWeek = {
  MONDAY: 0,
  TUESDAY: 1,
  WEDNESDAY: 2,
  THRUSDAY: 3,
  FRIDAY: 4,
  STAURDAY: 5,
  SUNDAY: 6
};

goog.object.extend(exports, proto.oojob.protobuf);
